# Use an official Node.js runtime as a parent image
FROM node:20

# # Make a directory for your application
WORKDIR /app

COPY . .

RUN npm install

# Install npm development dependencies
# Install Git (for use when using github pages functionality)
# Install Vim (for debugging)
RUN if [ "$NODE_ENV" != "production" ]; then echo $NODE_ENV && npm install --production=false && apt-get update && apt-get install -y git && apt-get install -y vim ; fi

RUN npm run build

EXPOSE 8000

CMD [ "npm", "run", "start" ]