# Use an official Node.js runtime as a parent image
FROM node:20

# # Make a directory for your application
WORKDIR /app

COPY . .

# Install npm dependencies, including non-production for build process
RUN npm install --include dev

# Install Vim - for debugging
# Install Git - for convenience when deploying with github pages functionality (npm run gsp:gh-pages)
RUN apt-get update && apt-get install -y git && apt-get install -y vim

# build production ready static files in ./dist directory
RUN npm run build

EXPOSE 8000

CMD [ "npm", "run", "start:dist" ]